language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator11.0

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail && xcodebuild build -workspace Exemple-ABSteppedProgressBar/Exemple.xcworkspace -scheme Exemple -sdk iphonesimulator11.0 ONLY_ACTIVE_ARCH=NO | xcpretty
